### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by creeper6530** [lilrosalyn/UwULogs#5]
Could you please add this plugin on Modrinth? I'd really like to add it to my Aternos server, but I need it to be on either one of these sites:
- [curseforge.com](https://www.curseforge.com/)
- [dev.bukkit.org](https://dev.bukkit.org/)
- [spigotmc.org](https://www.spigotmc.org/)
- [poggit.pmmp.io](https://poggit.pmmp.io/)
- [modrinth.com](https://modrinth.com/)

Modrinth would be preferred, as it's often considered the most reliable and overall best page of these five.

**Comment by lilrosalyn** [comment]
it's on modrinth now c:
https://modrinth.com/plugin/uwulogs
