### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by creeper6530** [lilrosalyn/UwULogs#6]
I'd be helpful to state which Minecraft versions this plugin works on. Also, build instructions would be appreciated too

**Comment by Atticuss26** [comment]
https://modrinth.com/plugin/uwulogs says here

**Comment by creeper6530** [comment]
Ok, and what about the building instructs? Also, mentioning the Modrinth page in the README would be useful, too.

**Comment by lilrosalyn** [comment]
You build UwULogs the same as any Maven plugin. You can open a terminal, and assuming you have Maven installed, you can run `mvn package` to build the plugin. I'll edit the README to include some instructions though.

**Comment by lilrosalyn** [comment]
README has been updated.

**Comment by creeper6530** [comment]
Thanks.
